[package]
name = "move-cli-readme"
version = "0.0.0"

[addresses]
Std = '0x1'

[dependencies.MoveNursery]
git = 'https://github.com/move-language/move.git'
subdir = 'language/move-stdlib/nursery'
rev = 'refs/remotes/origin/HEAD'