[package]
name = 'Econia'
version = '1.1.0' # Per SemVer

[addresses]
Econia = '0x389397a906ddab111bc8f8bfece404424d9da38f64e45f262e444281a2d71618'
TestUser = '0x1234'
TestUser1 = '0x2345'
TestUser2 = '0x3456'
TestUser3 = '0x4567'
TestUser4 = '0x5678'

[dependencies.AptosFramework]
git = 'https://github.com/aptos-labs/aptos-core'
subdir = 'aptos-move/framework/aptos-framework'
rev = 'a3143756d498821f4f51a5970c7ea35d483938b3'
