[package]
name = 'Ultima'
version = '0.1.0' # Per SemVer

# Named addresses should be in one of two forms, `long` or `short`.
# The Aptos blockchain uses long (32-byte) addresses, which are not
# compatible the Move command line tools, which only accept up to 16
# bytes in a single address
#
# Long form:
# Name = '0x1234567890123456789012345678901234567890123456789012345678901234'
#           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
# Up to 64 characters following the hex specifier (for Aptos)
#
# Short form:
# Name = '0x12345678901234567890123456789012' # '345678990123456789012345678901234'
#           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
# 32 characters following the hex specifier, followed by a space, a
# pound, a space, then the remaining address string. Additionally, they
# can be listed for even shorter forms, like those in AptosFramework
[addresses]
AptosFramework = '0x1'
Std = '0x1'
Ultima = '0xd5c9f830927dfd67fcfe55769a25988d' # 5bd6656b418bbcbf6f0d797d1ff37a64
TestUser = '0xace'

[dependencies.AptosFramework]
git = 'https://github.com/aptos-labs/aptos-core'
subdir = 'aptos-move/framework/aptos-framework'
rev = 'HEAD'

[dependencies.MoveStdlib]
git = 'https://github.com/move-language/move'
subdir = 'language/move-stdlib'
rev = 'HEAD'