[package]
name = 'ultima'
version = '0.1.0' # Per SemVer

[addresses]
AptosFramework = '0x1'
Std = '0x1'
Ultima = '0x931495623949281587790e4db840c8ffbad0829409223dc372661c3a4db20f2f'
TestUser1 = '0xace'
TestUser2 = '0xbed'

[dependencies.AptosFramework]
git = 'https://github.com/aptos-labs/aptos-core'
subdir = 'aptos-move/framework/aptos-framework'
rev = 'HEAD'

[dependencies.MoveStdlib]
git = 'https://github.com/move-language/move'
subdir = 'language/move-stdlib'
rev = 'HEAD'