[package]
name = 'ultima'
version = '0.1.0' # Per SemVer

[addresses]
AptosFramework = '0x1'
Std = '0x1'
Ultima = '0x2ed5db5c34b6bdac8236285b3f281f40f22d1a59c25be39e94dd67922c7cba02'
TestUser1 = '0xace'
TestUser2 = '0xbed'

[dependencies.AptosFramework]
git = 'https://github.com/aptos-labs/aptos-core'
subdir = 'aptos-move/framework/aptos-framework'
rev = 'HEAD'

[dependencies.MoveStdlib]
git = 'https://github.com/move-language/move'
subdir = 'language/move-stdlib'
rev = 'HEAD'