[package]
name = 'ultima'
version = '0.0.0'

[addresses]
AptosFramework = '0x1'
Std = '0x1'
Ultima = '0xf00cafe'
Art = '0xde5a31ee54e6db638a8e1ccf5aaeba86'

[dependencies.AptosFramework]
git = 'https://github.com/aptos-labs/aptos-core.git'
subdir = 'aptos-move/framework/aptos-framework'
rev = 'a4e8c42b61fcc963ad229c03408f045401d8f7e5'

[dependencies.MoveStdlib]
git = 'https://github.com/move-language/move.git'
subdir = 'language/move-stdlib'
rev = '2ab0b168c28504a3a586e64f9ae10f97f4b40b69'