[package]
name = 'ultima'
version = '0.0.0' # Should use SemVer

[addresses]
AptosFramework = '0x1'
Std = '0x1'
Ultima = '0xf00cafe'
Art = '0xde5a31ee54e6db638a8e1ccf5aaeba86'

[dependencies.AptosFramework]
git = 'https://github.com/aptos-labs/aptos-core'
subdir = 'aptos-move/framework/aptos-framework'
rev = 'HEAD'

[dependencies.MoveStdlib]
git = 'https://github.com/move-language/move'
subdir = 'language/move-stdlib'
rev = 'HEAD'