[package]
name = 'Ultima'
version = '0.1.0' # Per SemVer

[addresses]
AptosFramework = '0x1'
Std = '0x1'
Ultima = '0xf112ce1fb887b85dfef24068aff97749ad148989bd1a2ff8950206586e72a272'
TestUser = '0xace'

[dependencies.AptosFramework]
git = 'https://github.com/aptos-labs/aptos-core'
subdir = 'aptos-move/framework/aptos-framework'
rev = 'HEAD'

[dependencies.MoveStdlib]
git = 'https://github.com/move-language/move'
subdir = 'language/move-stdlib'
rev = 'HEAD'