[package]
name = 'ultima'
version = '0.1.0' # Per SemVer

[addresses]
AptosFramework = '0x1'
Std = '0x1'
Ultima = '0x264bfab8b0011957a49c893e1ab02476db1aba9ee0a3b8088271fb4a42100724'
TestUser1 = '0xace'
TestUser2 = '0xbed'

[dependencies.AptosFramework]
git = 'https://github.com/aptos-labs/aptos-core'
subdir = 'aptos-move/framework/aptos-framework'
rev = 'HEAD'

[dependencies.MoveStdlib]
git = 'https://github.com/move-language/move'
subdir = 'language/move-stdlib'
rev = 'HEAD'