[package]
name = 'Ultima'
version = '0.1.0' # Per SemVer

[addresses]
AptosFramework = '0x1'
Std = '0x1'
Ultima = '0x116ca02847a9ef95f6a9437152936ab242b4d00f4846e0f760ced2c497c6a4f9'
TestUser = '0xace'

[dependencies.AptosFramework]
git = 'https://github.com/aptos-labs/aptos-core'
subdir = 'aptos-move/framework/aptos-framework'
rev = 'HEAD'

[dependencies.MoveStdlib]
git = 'https://github.com/move-language/move'
subdir = 'language/move-stdlib'
rev = 'HEAD'